# 网站配置
title: Markor  # 网站标题
description: Markor for markdown  # 网站描述
baseurl: ""  # 网站的基本 URL，如果你的网站放在子目录中，则需要设置该选项
url: "https://zryyoung.github.io/markor"  # 网站的 URL
permalink: pretty  # 设置网址的格式，可选值为：pretty、date、ordinal、none

# Jekyll 配置
markdown: kramdown  # Markdown 引擎，可选值为 kramdown、redcarpet 等
theme: jekyll-theme-minimal  # 使用的 Jekyll 主题，替换为你选择的主题名称
plugins:
  - jekyll-feed  # 启用 Jekyll 插件，可选
  - jekyll-seo-tag  # 启用 Jekyll 插件，可选

# 作者信息
author:
  name: Markor  # 作者姓名
  email: zry5420@gmail.com  # 作者邮箱

# 社交链接
social:
  - title: Twitter
    url: https://twitter.com/johndoe
  - title: GitHub
    url: https://github.com/zryyoung

# 其他配置
paginate: 10  # 每页显示的文章数量
